apiVersion: v2
name: marketplace-app
description: Marketplace Microservices Application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: marketplace-app-api-gateway
    version: 0.1.0
    repository: "file://charts/api-gateway"

  - name: marketplace-app-auth-service
    version: 0.1.0
    repository: "file://charts/auth-service"

  - name: marketplace-app-kafka
    version: 0.1.0
    repository: "file://charts/kafka"

  - name: marketplace-app-order-service
    version: 0.1.0
    repository: "file://charts/order-service"

  - name: marketplace-app-payment-service
    version: 0.1.0
    repository: "file://charts/payment-service"

  - name: marketplace-app-product-service
    version: 0.1.0
    repository: "file://charts/product-service"
