replicaCount: 1

image:
  repository: kuraterut/marketplace-product-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
  annotations: {}
  host: product-service.example.com
  tls:
    secretName: tls-secret

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-product:5432/product_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_REDIS_HOST: keydb-product
  SPRING_REDIS_PORT: "6379"
  SERVER_PORT: "8082"

kafka:
  bootstrapServers: kafka:9092
  consumerGroupId: product-consuming-group

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
