apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product.fullname" . }}-config
  labels:
    {{- include "product.labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: 8082

    spring:
      application:
        name: product-service
      kafka:
        bootstrap-servers: {{ .Values.global.kafka.bootstrapServers }}
        consumer:
          group-id: {{ .Values.product.kafka.consumerGroup }}

    kafka-topics:
      order-created: {{ .Values.product.kafka.topics.orderCreated }}