{{- if .Values.product.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "product.fullname" . }}-hpa
  labels:
    {{- include "product.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "product.fullname" . }}
  minReplicas: {{ .Values.product.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.product.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.product.autoscaling.targetCPU }}
{{- end }}