apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-service.fullname" . }}-postgres
  labels:
    app: {{ include "payment-service.name" . }}-postgres
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  clusterIP: None
  selector:
    app: {{ include "payment-service.name" . }}-postgres
    release: {{ .Release.Name }}
