apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payment-service.fullname" . }}-postgres
  labels:
    app: {{ include "payment-service.name" . }}-postgres
    release: {{ .Release.Name }}
spec:
  serviceName: {{ include "payment-service.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "payment-service.name" . }}-postgres
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "payment-service.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "payment-service.fullname" . }}-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgresStorage.size }}
        storageClassName: {{ .Values.postgresStorage.storageClassName }}
