apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-service.fullname" . }}-secret
  labels:
    app: {{ include "payment-service.name" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  keydb-password: {{ .Values.keydb.password | b64enc | quote }}
