apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-app-kafka-config-template
data:
  advertised.listeners: "PLAINTEXT://{{ .Values.service.name }}-0.{{ .Values.service.name }}.default.svc.cluster.local:{{ .Values.service.port }}"
