apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: controller
      port: {{ .Values.service.controllerPort }}
      targetPort: {{ .Values.service.controllerPort }}
