apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      protocol: TCP
      name: kafka
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "kafka.fullname" . }}
