apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka.fullname" . }}
  serviceName: {{ include "kafka.serviceName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - name: datadir
              mountPath: /kafka-logs
            - name: config
              mountPath: /opt/bitnami/kafka/config/server.properties
              subPath: server.properties
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "{{ .Values.zookeeper.serviceName }}:2181"
            - name: KAFKA_CFG_LOG_RETENTION_HOURS
              value: "{{ .Values.config.logRetentionHours }}"
            - name: KAFKA_CFG_LOG_RETENTION_BYTES
              value: "{{ .Values.config.logRetentionBytes }}"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
          {{- toYaml .Values.resources | nindent 10 }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: {{ toJson .Values.persistence.accessModes }}
        storageClassName: {{ if .Values.persistence.storageClass }}{{ .Values.persistence.storageClass }}{{ else }}null{{ end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi
