server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres-product:5432/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

#logging:
#  level:
#    org.springframework: DEBUG
