apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "zookeeper.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  zoo.cfg: |
    tickTime={{ .Values.config.tickTime }}
    initLimit={{ .Values.config.initLimit }}
    syncLimit={{ .Values.config.syncLimit }}
    dataDir=/data
    clientPort=2181
    {{- range $i, $_ := until .Values.replicaCount }}
    server.{{ $i }}={{ include "zookeeper.fullname" $. }}-{{ $i }}:2888:3888
    {{- end }}
