server:
  port: 8080

spring:
  zipkin:
    base-url: http://zipkin:9411
    sleuth:
      sampler:
        probability: 1.0
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: marketplace-app-auth-service
          uri: http://marketplace-app-auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: marketplace-app-analytics-service
          uri: http://marketplace-app-analytics-service:8085
          predicates:
            - Path=/api/analytics/**
          filters:
            - name: CircuitBreaker
              args:
                name: analyticsServiceCircuitBreaker
                fallbackUri: forward:/fallback/analytics

        - id: marketplace-app-product-service
          uri: http://marketplace-app-product-service:8082
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product

        - id: marketplace-app-order-service
          uri: http://marketplace-app-order-service:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/order

        - id: marketplace-app-payment-service
          uri: http://marketplace-app-payment-service:8083
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

        - id: marketplace-app-product-service-docs
          uri: http://marketplace-app-product-service:8082
          predicates:
            - Path=/marketplace-app-product-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: marketplace-app-order-service-docs
          uri: http://marketplace-app-order-service:8084
          predicates:
            - Path=/marketplace-app-order-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: marketplace-app-payment-service-docs
          uri: http://marketplace-app-payment-service:8083
          predicates:
            - Path=/marketplace-app-payment-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: marketplace-app-auth-service-docs
          uri: http://marketplace-app-auth-service:8081
          predicates:
            - Path=/marketplace-app-auth-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1


    resilience4j:
      circuitbreaker:
        instances:
          authServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
            sliding-window-size: 10
          productServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
          orderServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
          bankAccountCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
          analyticsServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000





management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      http.server.requests: true
      tomcat: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    jdbc:
      include-parameter-values: true

springdoc:
  swagger-ui:
    urls:
      - name: marketplace-app-payment-service
        url: /marketplace-app-payment-service/v3/api-docs
      - name: marketplace-app-order-service
        url: /marketplace-app-order-service/v3/api-docs
      - name: marketplace-app-product-service
        url: /marketplace-app-product-service/v3/api-docs
      - name: marketplace-app-auth-service
        url: /marketplace-app-auth-service/v3/api-docs
      - name: marketplace-app-analytics-service
        url: /marketplace-app-analytics-service/v3/api-docs

    path: /swagger-ui.html

security:
  open-endpoints:
    - /marketplace-app-product-service/v3/api-docs
    - /marketplace-app-order-service/v3/api-docs
    - /marketplace-app-payment-service/v3/api-docs
    - /marketplace-app-auth-service/v3/api-docs
    - /marketplace-app-analytics-service/v3/api/docs
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/auth/login
    - /api/auth/register
    - /api/analytics/stats
    - /actuator/health



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG