server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/order

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: payment-service-docs
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - name: StripPrefix
              args:
                parts: 1


    circuitbreaker:
      resilience4j:
        instances:
          authServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
            sliding-window-size: 10
          productServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
          orderServiceCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000
          bankAccountCircuitBreaker:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    urls:
      - name: payment-service
        url: /payment-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
      - name: auth-service
        url: /auth-service/v3/api-docs

    path: /swagger-ui.html

security:
  open-endpoints:
    - /product-service/v3/api-docs
    - /order-service/v3/api-docs
    - /payment-service/v3/api-docs
    - /auth-service/v3/api-docs
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/auth/login
    - /api/auth/register
    - /actuator/health



#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    io.github.resilience4j: DEBUG