{{- if .Values.keydb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}-keydb
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ include "auth-service.fullname" . }}-keydb
{{- end }}
