{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "auth-service.fullname" . }}-postgres
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "auth-service.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "auth-service.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "auth-service.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.postgresSecretName" . }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.postgresSecretName" . }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.postgresSecretName" . }}
                  key: database
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
