{{- if and (not .Values.postgresql.existingSecret) .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.postgresSecretName" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.postgresql.username }}"
  password: "{{ .Values.postgresql.password }}"
  database: "{{ .Values.postgresql.database }}"
{{- end }}
