apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 3
  maxReplicas: 15  # Высокий максимум для пиковых нагрузок
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Консервативный порог
    - type: External
      external:
        metric:
          name: kafka_topic_partition_lag
          selector:
            matchLabels:
              topic: payment-request
        target:
          type: AverageValue
          averageValue: "100"  # Жесткий контроль лага