apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "order-service.fullname" . }}-postgres
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: postgres
      release: {{ .Release.Name }}
  serviceName: {{ include "order-service.fullname" . }}-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "order-service.fullname" . }}-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
        storageClassName: {{ .Values.postgres.persistence.storageClass | default "standard" }}
