apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  labels:
    app: {{ include "order-service.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
