apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eureka-server.fullname" . }}
  labels:
    {{- include "eureka-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "eureka-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eureka-server.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: eureka-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: http
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{.Values.global.eureka.serviceUrl | quote}}
            - name: SPRING_APPLICATION_NAME
              value: "eureka-server"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 30
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
