sonar.projectKey=marketplace-payment-service
sonar.projectName=Payments Service
sonar.host.url=http://localhost:9000
sonar.token=squ_9dbd06cd68b0069e4ac96fc1c7bdc446fad199f7
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/model/**, **/dto/**, **/config/**, **/mapper/**

# ????
sonar.sources=src/main/java
sonar.tests=src/test/java

# ???????? (???? Maven/Gradle ?? ?????????? ?????????????)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
