server:
  port: 8083

spring:
  application:
    name: bank-account-service
  datasource:
    url: jdbc:postgresql://postgres-bank-account:5432/bank_account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    #TODO Включить ликвибэйз
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

#logging:
#  level:
#    org.springframework: DEBUG
