server:
  port: 8085

spring:
  zipkin:
    base-url: http://zipkin:9411
    sleuth:
      sampler:
        probability: 1.0

  application:
    name: marketplace-app-analytics-service

  kafka:
    bootstrap-servers: marketplace-app-kafka:9092
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:ch://clickhouse-analytics:8123/analytics
    username: kuraterut
    password: kuraterut
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    jdbc:
      include-parameter-values: true
