apiVersion: v1
kind: Service
metadata:
  name: postgres-payment-service-headless
  labels:
    app: postgres-payment
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
    - port: 8008
      name: patroni
  selector:
    app: postgres-payment