apiVersion: v1
kind: Service
metadata:
  name: postgres-order-service
  labels:
    app: postgres-order
    role: master
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres-order
    role: master
  type: ClusterIP