apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.name" . }}-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote}}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active | quote }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eureka.serviceUrl | quote }}
  JWT_SECRET: "{{ .Values.global.jwt.secret}}"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "DEBUG"
