apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  application.yaml: |
    server:
      port: 8084
    
    spring:
      application:
        name: order-service
      cache:
        type: redis
        redis:
          time-to-live: 3600000
          key-prefix: "order-service:"
      kafka:
        bootstrap-servers: kafka:9092
        consumer:
          group-id: order-consuming-group
          isolation-level: read_committed
    
    kafka-topics:
      payment-result: payment-result
      product-hold-success: product-hold-success
    
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka
    
    scheduling:
      process-payment-event-rate: 3000