apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  application.yaml: |
    server:
      port: 8082
    
    spring:
      application:
        name: product-service
      cache:
        type: redis
        redis:
          time-to-live: 3600000
          key-prefix: "product_service:"
      kafka:
        bootstrap-servers: kafka:9092
        consumer:
          group-id: product-consuming-group
          auto-offset-reset: earliest
    
    kafka-topics:
      order-created: order-created
      product-hold-failed: product-hold-failed
    
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka