apiVersion: v1
kind: Service
metadata:
  name: keydb-payment-headless
  labels:
    app: keydb-payment
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    app: keydb-payment