apiVersion: v1
kind: Service
metadata:
  name: keydb-product
  labels:
    app: keydb-product
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    app: keydb-product
