apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "product-service.fullname" . }}-keydb
  labels:
    app: keydb
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: keydb
      release: {{ .Release.Name }}
  serviceName: {{ include "product-service.fullname" . }}-keydb
  replicas: 1
  template:
    metadata:
      labels:
        app: keydb
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: keydb
          image: eqalpha/keydb:latest
          ports:
            - containerPort: 6379
              name: keydb
          volumeMounts:
            - name: keydb-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: keydb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.keydb.persistence.size }}
        storageClassName: {{ .Values.keydb.persistence.storageClass | default "standard" }}
