apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  labels:
    app: postgres-product
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-product
