apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}-secret
  labels:
    app: {{ include "product-service.name" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
